### ISSUE TITLE
latest img not found

### ISSUE THREAD

**Issue by MalloZup** [Pajinek/docker-spacewalk-client#3]
Ciao @Pajinek,

``` console
docker pull pajinek/spacewalk-client
Using default tag: latest
Pulling repository docker.io/pajinek/spacewalk-client
Error: image pajinek/spacewalk-client:latest not found
```

https://hub.docker.com/r/pajinek/docker-spacewalk-client/builds/b58gmfue4y4oxep4r5gvat/

Hope it helps!

**Comment by Pajinek** [comment]
correct name of image is **pajinek/docker-spacewalk-client**

using: docker pull pajinek/docker-spacewalk-client

I fixed it in readme file. Thanks

**Comment by MalloZup** [comment]
ok tested it works. thx
